name: 'Deploy blog'

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  blog-deployment:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    
    steps:
    - name: Checkout source
      uses: actions/checkout@v6
      with:
        submodules: true
    
    - name: Setup nodejs
      uses: actions/setup-node@v6
      with:
        node-version: '24.x'
    
    - name: Install dependencies
      run: |
        node -v
        npm i

    - name: Generate static files
      run: |
        npm run build

    - name: Ensure vue router works on github pages
      run: |
        cp dist/index.html dist/404.html
    
    - name: Deploy to gh-pages branch
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
